apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: spring-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-server
  template:
    metadata:
      labels:
        app: spring-server
    spec:
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
      - name: spring-web-server
        image: dlskawo0409/spring_test4
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: "/home/share/nfs"
            name: my-pv-storage
        imagePullPolicy: Never

      nodeSelector:
        key: master
---
apiVersion: v1
kind: Service
metadata:
  name: spring-web-server-service
spec:
  ports:
    - name: "8080"
      port: 8081
      targetPort: 8080
      nodePort: 30600
  selector:
    app: spring-server
  type: NodePort

